# Generated by Django 3.2.16 on 2023-01-03 16:50

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_theme',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
